### ISSUE TITLE
Writing JSON string drops bracket in serilog output

### ISSUE THREAD

**Issue by KurtVD** [serilog/serilog-sinks-file#102]
Hello,

When I want to write a message which contains a JSON string to my log file, somehow I lose a bracket in the resulting output in the log file.

See my demo project to reproduce this here:
https://github.com/KurtVD/SerilogTester

I'm using .NET Core 2.1.0 with Serilog.Sinks.File 4.0.0

The JSON string contains }}} which is changed to }} when outputting this with Serilog, resulting in an invalid json string in the log file.

I've added in comment the correct JSON structure I'm adding as a string (see first comment in code), and the resulting wrong JSON structure in the logfile output (see second comment in code). I've marked where the bracket is missing.

Is it because I'm doing something wrong when writing the message with serilog?
How can I manage writing this JSON string correctly to the log file?
In my real world project, I'm also writing other messages to the log, not only json strings.

**Comment by tsimbalar** [comment]
You should never use `$` strings when calling Serilog Log methods : see https://nblumhardt.com/2015/01/c-6-string-interpolation-and-serilog/

You should replace : 

```cs
log.Information($"JSON = {json}");
```

( which ends up being replaced with `Log.Information("\"{\"event_location\" ....");` and Serilog tries to parse it as a messageTemplate ... which it is not :P ) 

with

```cs
log.Information("JSON = {MyJsonString}", json);
```

But all in all, you'd be better off logging the "object" instead of the "JSON representation" of the object, I think ;)

**Comment by KurtVD** [comment]
Thanks for the feedback!

Using the object didn't work out for me, as I have different object property names compared to what I need in the JSON string.

But this worked out just fine:
`log.Information("JSON = {MyJsonString:l}", json);`

I had to specify :l literal format specifier on the property to get rid of escaped quotes in the log output.
Using log.Information("JSON = {MyJsonString}", json);
