### ISSUE TITLE
[New Feature] RollingInterval.EachRun....

### ISSUE THREAD

**Issue by natiki** [serilog/serilog-sinks-file#108]
Hi,

I often have the need to write out a log file for each run of an application. It would be nice if this was supported directly. It could be as simple as appending miliseconds:

`
yyyyMMddHHmmfff
`

**Comment by cocowalla** [comment]
You can do this already, but only with programmatic configuration of the sink. E.g.:

```
var suffix = DateTime.UtcNow.ToString("yyyyMMddHHmmssfff");

var log = new LoggerConfiguration()
    .WriteTo.File($"file-{suffix}.txt")
    .CreateLogger();
```

**Comment by natiki** [comment]
@cocowalla Thanks will do that in the mean time. Would be nice however to have this as a configuration option directly.

**Comment by nblumhardt** [comment]
Thanks for the notes, @natiki .

I don't think it's likely we'll add this in the near future, since the alternative is so compact. Building it in would have the advantage of adding config file support, but its still on the borderline.

I'll close this for now but it's a useful record in the case that this request ends up being raised repeatedly. Thanks again! 👍
