### ISSUE TITLE
{{ and }} to file is { and } 

### ISSUE THREAD

**Issue by mywand** [serilog/serilog-sinks-file#110]
![图片](https://user-images.githubusercontent.com/13902074/63587498-c036c980-c5d6-11e9-9bfc-c29ca3e40e56.png)

**Comment by tsimbalar** [comment]
Hi,

This is the expected behavior.

``{{`` and `}}`` are respectively the escaped version of `{` and `}`. 
Normally, a single `{Something}` has a special meaning for serilog (would be replaced with the value of `Something`), so if you want to write out a `{` you have to double it.

You can check the syntax reference in the main serilog repo's wiki : https://github.com/serilog/serilog/wiki/Writing-Log-Events#message-template-syntax , this sentence in particular : 

> - Brackets can be escaped by doubling them, e.g. ``{{`` will be rendered as `{`

I hope this helps .
