### ISSUE TITLE
Ability to rotate log files with main file not changing name

### ISSUE THREAD

**Issue by numito** [serilog/serilog-sinks-file#118]
Hello,

Serilog file sink allows to rotate log file. On each rotation a new file will be created and the log will be written in this file. Therefor the file name changes on each rotation.  Some active firewall software such as fail2ban won't work if the file name keeps on changing, as it wouldn't know which will be the next file name. 
Therefor I have modified  serilog sink file to add a configuration parameter so it always write to the same filename. On each file rotation the current file is copied to a new name, and the current file is emptied.

I would like to contribute my changes, are you interested ? 

Best regards,
Numa

**Comment by cocowalla** [comment]
Hi, the behaviour you are referring to is already discussed by #40, so it would be better if any discussion could continue over there - thanks!

If I can summarise for you here though:

- A lot of people are interested in this functionality
- It may be tricky to get right
- Rather than replacing existing functionality, we should come up with a system than enabled pluggable naming/rolling policies

If you could come up with an API proposal for that last point, it would be really helpful to moving this forward :smile: 

Would also be helpful if you could push your fork so others could see it.
