### ISSUE TITLE
Warning not logged without Visual Studio launch

### ISSUE THREAD

**Issue by cnayan** [serilog/serilog-sinks-file#126]
Console project based on dotnet core 2.1

When I print a warning, when app is run via Visual Studio 2019 Pro, I can see the warning generated in the log file.
When I run from console "dotnet <dll-name>", or as published exe, the warning is missing in the file.

Code:

```
private static void SetupLogger(IConfiguration config)
{
        var @switch = new LoggingLevelSwitch();
        @switch.MinimumLevel = LogEventLevel.Information;
	var loggerConfiguration = new LoggerConfiguration().MinimumLevel.ControlledBy(@switch);
	loggerConfiguration.ReadFrom.Configuration(config);
	Serilog.Log.Logger = loggerConfiguration.CreateLogger();
}
```

Config:

```
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console" ],
    "MinimumLevel": "Debug",
    "Override": {
      "Microsoft": "Warning",
      "System": "Warning"
    },
    "WriteTo": [
	  { "Name": "File", "Args": { "path": "D:\\Code\\test.log" } }
    ]
  }
```

**Comment by cnayan** [comment]
I also have this in code, if it helps:

`AppDomain.CurrentDomain.ProcessExit += (s, e) => Serilog.Log.CloseAndFlush();`

**Comment by nblumhardt** [comment]
Hi Nayan, thanks for getting in touch.

There could be a number of issues - log file opened twice in the same process; log file locked by another process; Serilog.Sinks.File missing from the published app; config file not found when the published app is loaded - do any of these spark any ideas?

Since it's unlikely the issue will be with the sink itself (it's very very widely-used) it will be worth digging into other parts of your project setup/environment to see where things may have gone wrong.

Hope this helps,
Nick

**Comment by cnayan** [comment]
Thank you for responding.

1) Log file opened twice: Is file sink opening it multiple times? Can you share more on how to debug this?

2) File locked by another process: I feel this should not be the case as info messages are present in the same situation. Plus, the file is not locked, i verified.

3) Sink assembly missing: As said above, the info is present in the file. This cannot happen if assembly is missing. I verified the presence of the assembly in the folder.

4) Config file missing: Not the case, as I verified. But I'm hoping this be the case of dishonored config.

Any thoughts? What's the way to dig deeper?

Thank you once again!

**Comment by cnayan** [comment]
Sorry to waste your time. It works.
I had a conditional flow in my code for warning which blocked the log. :-(

Thank you for help!
