### ISSUE TITLE
Unpin assembly version

### ISSUE THREAD

**Issue by TylerLeonhardt** [serilog/serilog-sinks-file#135]
Looks like the [assembly version](https://github.com/serilog/serilog-sinks-file/blob/master/src/Serilog.Sinks.File/Properties/AssemblyInfo.cs#L5) is out of sync with the [actual version](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Serilog.Sinks.File.csproj#L5).

This causes issues when loading from the GAC on .NET Framework because if v3 of `Serilog.Sinks.File` is loaded in the GAC with assembly version 2.0.0.0... and we depend on `Serilog.Sinks.File` v4 functionality... things won't work.

As seen here: https://github.com/PowerShell/vscode-powershell/issues/2538

**Comment by rjmholt** [comment]
See https://github.com/PowerShell/vscode-powershell/issues/2538#issuecomment-596825533 and https://github.com/PowerShell/vscode-powershell/issues/2538#issuecomment-597178077 for the particular breakdown of the issue.

I see in https://github.com/serilog/serilog/issues/1319 that this is by design. Is there a way to ensure we load the right DLL?

**Comment by nblumhardt** [comment]
Probably time to unpin, now that the NuGet/.NET ecosystem has settled down a bit around this :+1:

**Comment by dkattan** [comment]
What are the next steps here? 

What's the worst that can happen if we unpin the version?

**Comment by nblumhardt** [comment]
@dkattan let's find out! :-)

(Most likely - we'll see an uptick in support requests from folks whose tooling doesn't generate binding redirects correctly, which was a major pain in the past, but should hopefully be less so now.)
