### ISSUE TITLE
Installing on .net core 3.1 app require 12 dependencies instead of 4.

### ISSUE THREAD

**Issue by DmytroLohvynenko** [serilog/serilog-sinks-file#139]
In nuget package description stated that for .net standard 2.0 it should be only 4 dependencies.
![image](https://user-images.githubusercontent.com/25682289/79310454-a8fd7100-7f04-11ea-9038-fcb8fd6dcec9.png)

But when I try to install on .net core 3.1 console app, I see prompt with 12 dependencies. Is is correct?
![image](https://user-images.githubusercontent.com/25682289/79310437-9edb7280-7f04-11ea-917a-36880b0715cd.png)

**Comment by nblumhardt** [comment]
Hi! May be related to #104 - can you please try out the latest `-dev` release of this package? Thanks!

**Comment by Numpsy** [comment]
Same thing here - installing the 5.0.0 dev release into a .NET Core 3.1 console app only wants Serilog, but installing it into a Core 2.1 app or a .NET Standard 2.1 library wants many more (because System.IO.FileSystem has a bunch of dependencies of it's own?):

![image](https://user-images.githubusercontent.com/1178570/85805995-c4c39580-b745-11ea-836a-fb29a3cb1e06.png)

As the comment in #130 says, is there a need for those extra libs when targetting Standard 2.1 or 2.0?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I think we'll get diminishing returns trying to modify the dependency graph targeting older .NET Core versions; since all is fine on 3.1 let's close this now.
