### ISSUE TITLE
Set correct file permissions on Linux

### ISSUE THREAD

**Issue by etamminga** [serilog/serilog-sinks-file#169]
Hi,

How can I configure serilog.sinks.file to create files with 640 (user rw, group r, other -) permisions on linux?

Regards,
Erik

**Comment by cocowalla** [comment]
This sink doesn't do anything in particular with permissions.

I think the best approach here is to create the directory in advance, setting the setuid (sticky user) bit on it so that new files will automatically get the same group as the folder. You can then also set default permissions for that group using `setfacl`.

Hope this works for you 👍

**Comment by etamminga** [comment]
Yes thank you!
Just my unfamiliarity with Linux ;)
