### ISSUE TITLE
Investigate support for `O_APPEND` on Linux

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-file#173]
See: https://nblumhardt.com/2016/08/atomic-shared-log-file-writes/

I'd guess by now there will be options/support for this in .NET Core, time to come back around to it.

**Comment by tjmoore** [comment]
Any news on this? This may be a solution to an issue we see with logrotate which causes huge amounts of nulls to appear in the log files. A suggestion is this is caused by not opening the file with O_APPEND. https://stackoverflow.com/questions/64871670/null-value-in-the-beginning-of-log-after-logrotate

**Comment by nblumhardt** [comment]
@tjmoore no news, though there were some moves being made to support `O_APPEND` on Linux in .NET 6, which could use another look. Any help with investigation would be appreciated :+1:

**Comment by nblumhardt** [comment]
Superseded by #221
