### ISSUE TITLE
[Question] How can I customize Args of FileSink?

### ISSUE THREAD

**Issue by Kamil-Zakiev** [serilog/serilog-sinks-file#184]
Hello!

I'm configuring FileSink using appsettings.json and I want the path to include current time stamp, for example:
~WorkerService\bin\Debug\net5.0\\**temp-2020-10-08-17-29-39**

Please clarify how I can achieve this via appsettings (if it's even possible)

**Comment by bartelink** [comment]
Best to ask this sort of question on stackoverflow - you'll get many more eyes, and a much quicker answer

**Comment by cocowalla** [comment]
I don't believe it's possible to use any kind of token in the path, and Serilog only uses date/sequence tokens in the filename in a fixed way.

Off the top of my head, allowing user-defined tokens and/or dynamic paths, is going to break the file retention function - Serilog needs a fixed directory and filename format in order to know when to delete old files.

**Comment by Kamil-Zakiev** [comment]
Thanks for suggestion, @bartelink :)

@cocowalla, your considerations sound reasonable: custom token support would complicate file retention feature, thanks for sharing your thoughts!
