### ISSUE TITLE
Append an encrypted file

### ISSUE THREAD

**Issue by Falco20019** [serilog/serilog-sinks-file#199]
Right now, we use the `FileLifecycleHooks` to encrypt our logging. This works great, as long as we don’t try to append to this file after it was closed (due to the final Block with padding). Sadly, the stream of `FileSink` is opened only for `Write` with `FileShare.Read`. Due to our configuration, this is additionally wrapped in `WriteCountingStream`. The `FileStream` itself would be seekable (`CanSeek` is also true on `WriteCountingStream`, but the `Seek` method was overwritten to throw an exception which feels misleading).

After seeing #189, I wanted to open the file for reading, extract the last two blocks, encrypt the last one with the second to last as IV, reset the cursor using `Seek` by one block and afterwards rewrite the last block without padding to the given stream, keeping the stream open for all further operations. This only works, when `WriteCountingStream` is out of the game.

The alternative would be to have the stream opened with `ReadWrite` permission. In this case, we would still need the `WriteCountingStream` to allow seeking (for overwriting the last block), but don’t need a second stream on the same file.

The best option for me would be to have a pre-hook to just being called before the file is opened (so that I can open the file with any permission needed and prepare it). This way, I could get the IV and the last block or even remove the last block already. When the file is opened, I could wrap the stream opened by the sink and write the last block. This way, I don’t even need `WriteCountingStream` to be seekable.

But as it is now, it‘s hard to append to encrypted files. So to circumvent the files getting corrupted, we throw an `IOException` if the underlying stream is not empty to force-start a new file on the `RollingFileSink`. I also found no other workaround to enforce the start of the next file.

Maybe I am just missing something. So if anyone has already done encryption on the logging, just let me know! Every help is appreciated.

**Comment by nblumhardt** [comment]
Hi! We're triaging issues in this tracker and the current one appears to be stale. If your issue relates to a usage question, asking on Stack Overflow and posting a link here will get the most eyes on it (only a small number of maintainers actively track this repository). If your issue relates to a possible bug that still needs attention, please feel free to comment/request reopening. Thanks!

**Comment by byte2pixel** [comment]
I realize this issue is quite old, but for anyone who comes across it in the future, I wanted to share my experience implementing encrypted logging with Serilog.

In my approach, each time the file is opened, it starts a new encryption session. This avoids issues with appending to encrypted files, as each session is self-contained. I use hybrid encryption: AES-GCM for encrypting log messages and RSA for encrypting the random AES session information as metadata. Each write uses a new nonce, and key rotation is also possible, allowing different parts of the log to be encrypted with different keys.

Appending works reliably because, during decryption, the process simply parses session headers, uses an interface to call a KMS or other implementation to decrypt the AES session key with RSA, and then decrypts the log messages with AES. The decryption logic does not depend on how many times the file was opened or closed.

If it’s helpful, I’ve open-sourced my implementation here: https://github.com/byte2pixel/serilog-sinks-file-encrypt

Hope this helps anyone looking to implement encrypted logging with Serilog!
