### ISSUE TITLE
Breaks if path becomes unavailable

### ISSUE THREAD

**Issue by kid101skater** [serilog/serilog-sinks-file#208]
This breaks if the path to the log file is no longer available.
Example: Writing Logs to a USB drive - usb drive becomes disconnected - then is reconnected. 
Example: Shared network path becomes unavailable due to network connection disruption - network comes back and now that path is available, log stops writing. 

Fix:
Change i had submitted for a PR. Check that the path root is available.

**Comment by cocowalla** [comment]
Few questions:

1. Let's say you are writing logs to a Samba share, and the network is disconnected:
  - if we check before every emit to check if the path is still available, there is always going to be a race condition there, so this is not guaranteed to work all the time
  - we could instead swallow exceptions, but that is likely going hurt performance a bit, and feels wrong
2.  Let's say either (1) or (2) above is implemented - what happens to logs as the sink keeps writing them? Are they buffered in memory? If so, for how long, or up to what size? What if buffering is disabled? Does flushing to the file resume automagically once the network is back up? Is the result the same for Windows, Linux and MacOS? Is the result the same for different sources (local USB, remote Samba, remote NFS...)?

OK, that 2nd question was about 10 questions 😉, but I think it demonstrates that this is not a simple problem to solve - if you want this to work consistently across all platforms, destinations and edge cases, it's going to get complicated. And writing tests for this kind of thing would also be very tricky.

This sink has remained so approachable because it's svelte, and doesn't try to do everything - I wonder if this is one of those cases that is best handled another way? Maybe some kind of watchdog that restarts the service if the network goes down and comes back up?

**Comment by kid101skater** [comment]
Hi:

So i believe this is same issue as my example with usb - i had done multiple back to back tests to validate that the potential change would in fact work - even when the drive needed to be formatted before being read. All passed.

As far as logs being stored in memory, it will currently just not write the logs that it missed - it will just continue writing once the path is available. Essentially, your logs during the time of disconnect will not be written.

**Comment by nblumhardt** [comment]
Hi! We're triaging issues in this tracker and the current one appears to be stale. If your issue relates to a usage question, asking on Stack Overflow and posting a link here will get the most eyes on it (only a small number of maintainers actively track this repository). If your issue relates to a possible bug that still needs attention, please feel free to comment/request reopening. Thanks!
