### ISSUE TITLE
System.Runtime 5.0.0.0 dependency after updating to last version

### ISSUE THREAD

**Issue by ruipaulomonteiro** [serilog/serilog-sinks-file#229]
Hi,

I have a .net 4.8 project (Windows Service) that depends on a .net standard 2.0 project with classes for log management through serilog. 

It was working fine with version 4.1.0 but after updating to version 5.0.0, I started to get the following error when the log initialization is triggered: 
"Could not load file or assembly System.Runtime, Version=5.0.0.0"

Apparently the dependency reference is correct, it seems to look for .net 5 runtime when running.

![image](https://user-images.githubusercontent.com/13275395/124195966-538a9100-dac3-11eb-9379-b7dadd854c71.png)

Any help would be appreciated. Thanks in advance.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, that's rather strange!

The 5.0 `netstandard2.0` version doesn't look to have any strange dependencies:

![image](https://user-images.githubusercontent.com/342712/124226172-00105580-db4c-11eb-827f-2edf099bfacf.png)

Just some ideas that might help narrow this down-

 - Is the .NET Standard project in the same solution, or are you consuming it as a library?
 - Is your project a new-style or old-style CSPROJ?
 - Have you tried completely cleaning and rebuilding?
 - Do you have .NET 5 installed at all? (Not sure how this would/should impact it .. but .. >???)
 - Do you know which MSBuild binary you're building with?
 - Does it work if you build using `dotnet build` instead of VS?

**Comment by ruipaulomonteiro** [comment]
Hi,

Thanks for the hints. Checked all and seems to be ok. When activating build verbose output, found this message which seems to be the cause. But didn't find out why the 5.0.0.0 version is required. 
Still looking....

8>  MSB3243: No way to resolve conflict between "System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily. (TaskId:25)
8>      References which depend on "System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
8>          C:\prjNet\CSU\ADD-ON\Master Data\Implementação\Output\Platform\Serilog.Sinks.File.dll
8>            Project file item includes which caused reference "C:\prjNet\CSU\ADD-ON\Master **Data\Implementação\Output\Platform\**Serilog.Sinks.File.dll**".**

**Comment by nblumhardt** [comment]
Looking at #232, any chance adding the below to your CSPROJ fixes it?

```xml
<PackageReference Include="Microsoft.NETCore.Targets" Version="5.0.0" PrivateAssets="all" />
```

**Comment by juanmalm** [comment]
Same issue here. Cannot update to 5.0.0.

**Comment by bartelink** [comment]
Hi, I'm soring cleaning the issues lsit. I feel this issue is just confusing, so ideally we'd shift it to either
a) closed
or b) a clear problem definition (ideally with a documented workaround)

I suspect there likely is a workaround given the lack of traffic on this issue atm

@juanmalm have you found a solution?
@ruipaulomonteiro did you try Nicks's suggestion?

**Comment by juanmalm** [comment]
> Hi, I'm soring cleaning the issues lsit. I feel this issue is just confusing, so ideally we'd shift it to either a) closed or b) a clear problem definition (ideally with a documented workaround)
> 
> I suspect there likely is a workaround given the lack of traffic on this issue atm
> 
> @juanmalm have you found a solution? @ruipaulomonteiro did you try Nicks's suggestion?

Nope

**Comment by ruipaulomonteiro** [comment]
Could not explain why but I rebuilt all from scratch and started working. Thanks!

**Comment by bartelink** [comment]
Thanks @ruipaulomonteiro for circling back (and closing - hopefully the 11 remaining issues now correctly represent the actionable enhancements and/or investigations that this repo is the right place for...)

@juanmalm if you're still blocked, I'd suggest trying Nick's suggestion, and then creating a stack overflow question tagged `serilog` documenting:
- what you tried
- the exact issue/message on which you are blocked
and posting a link to it here.
