### ISSUE TITLE
Consistency issue with RollingFileSink and FileLifeCycleHooks

### ISSUE THREAD

**Issue by kemsky** [serilog/serilog-sinks-file#233]
There is the following code:

```csharp
            foreach (var obsolete in toRemove)
            {
                var fullPath = Path.Combine(_roller.LogFileDirectory, obsolete);
                try
                {
                    _hooks?.OnFileDeleting(fullPath);
                    System.IO.File.Delete(fullPath);
                }
                catch (Exception ex)
                {
                    SelfLog.WriteLine("Error {0} while processing obsolete log file {1}", ex, fullPath);
                }
            }
```

The code above is not transactional and makes it difficult to handle errors. 

For example, `serilog-sinks-file-archive` has created an archive, but `System.IO.File.Delete(fullPath)` failed because the file could be still in use, so next time hooks will fire again for the same file, but archived log may already exist... 

It can actually indicate some other bug because files are not released sometimes under IIS.

I think it makes sense at least to test that file can be deleted before executing hooks e.g.:

```csharp
        private bool IsFileLocked([NotNull] string path)
        {
            try
            {
                var file = new FileInfo(path);

                using (var stream = file.Open(FileMode.Open, FileAccess.Read, FileShare.None))
                {
                    stream.Close();
                }
            }
            catch (IOException)
            {
                //the file is unavailable because it is:
                //still being written to
                //or being processed by another thread
                //or does not exist (has already been processed)
                return true;
            }

            //file is not locked
            return false;
        }
```

**Comment by cocowalla** [comment]
I haven't given too much thought to this yet, but a couple of points sprang immediately to mind:

- I've made plenty use of this hook, and haven't come across this issue; given the code, it doesn't look like Serilog itself is doing anything wrong here - you mention IIS, so presumably files remaining locked is a localised issue

- there is kind of a race condition with `IsFileLocked`, in that it may say "file is locked", but the file may be unlocked a nanosecond later

- allowing the hook author to handle errors means they can implement retries if wanted - so you can wait for the file to become available, or not. My feeling is that retries are the best solution, as long as this issue is indeed an I Is-specific problem

**Comment by kemsky** [comment]
@cocowalla, we do not use your hook directly, it is a customized version that uses zip instead of gzip.  

Sometimes it fails:

```csharp
System.IO.IOException: The process cannot access the file 'c:\Logs\sync20210629.txt' because it is being used by another process.
  ?, in void __Error.WinIOError(int errorCode, string maybeFullPath)
  ?, in void FileStream.Init(string path, FileMode mode, FileAccess access, int rights, bool useRights, FileShare share, int bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, string msgPath, bool bFromProxy, bool useLongPath, bool checkHost)
  ?, in new FileStream(string path, FileMode mode, FileAccess access, FileShare share)
  ?, in ZipArchiveEntry ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, string sourceFileName, string entryName, CompressionLevel? compressionLevel)
  File "C:\BuildAgent\work\c957590b7355bed8\Logging\Hooks\ArchiveHooks.cs", line 40, col 21, in void ArchiveHooks.OnFileDeleting(string path)
```

Windows says that the file is locked by the IIS Worker thread. Process Explorer shows a number of locked log files.

The only other place where we access log files directly is the following code:

```csharp
 using (var fileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
 using (var stream = MemoryStream())
 {
      await fileStream.CopyToAsync(stream);
      bytes = stream.ToArray();
 }
```

 It is not cool but should not hold any locks ...  It can also be a problem with Serilog or Serilog Sink.

Configuration is simple:
```csharp
configuration
                .WriteTo
                .Async(x =>
                {
                    x.Logger(cfg =>
                    {
                        cfg
                            .WriteTo
                            .File(filePath, LogEventLevel.Debug, applicationConfiguration.LoggerFileTemplate, formatProvider, hooks: new ArchiveHooks(), rollingInterval: RollingInterval.Day, retainedFileCountLimit: 5);
                    });
                })
```

The idea is to use `IsFileLocked` to provide at least a minimal guarantee that the file is not locked otherwise just skip removal of the obsolete locked file and hook execution.

Retries do not cover all possible scenarios, file can remain locked until the server restarts.

**Comment by cocowalla** [comment]
> The only other place where we access log files directly is the following code:
> ...

I don't know where or how often you are running that code, but it will lock the file until the `FileStream` is disposed, preventing deletion.

One of the principles behind Serilog is to keep it as simple as possible, while still being extensible so sinks can be forked if needed for edge cases. Since it appears to be a 3rd party product (IIS) misbehaving, I'm thinking a fork may be the best option here.

Out of interest, does anything change if you don't configure the sink to write logs using a background thread (with `.Async`)? It's relatively unusual to use this for file-based logs, unless you are writing enormous volumes and/or you don't care about logs being lost in a crash. More to the point though, long ago when I used to regularly use IIS, I recall background threads were finicky - for example, with Hangfure I remember having to configure quite a few settings to prevent IIS recycling the threads.

**Comment by kemsky** [comment]
@cocowalla, removing `.Async` did not help, looks like I will have to try to explicitly shut down the logger.

**Comment by kemsky** [comment]
@cocowalla, 

> I will have to try to explicitly shut down the logger.

This helps, files are not leaking anymore. Probably it makes sense to wrap FileStream reference into SafeHandle. See http://joeduffyblog.com/2005/12/27/never-write-a-finalizer-again-well-almost-never/.

**Comment by kemsky** [comment]
There is still one minor issue, sometimes hook fails because the file already exists (Exception), but when I check the file system there is no file. Looks like a race condition or cleanup problem. I will try to investigate.

**Comment by kemsky** [comment]
@cocowalla, the original issue holds true, sometimes delete fails and the hook tries to archive the same log file again and fails because the zip file already exists, so I had to modify the hook to replace the existing file.

**Comment by nblumhardt** [comment]
Thanks for the follow-up @kemsky. Seems like a deployment-specific problem at this point, but if you find a race in the Serilog side of it please do let us know 👍
