### ISSUE TITLE
Log file ending up in project directory

### ISSUE THREAD

**Issue by silkfire** [serilog/serilog-sinks-file#235]
Using the following setup:

```
{
  "Serilog": {
      {
        "Name": "File",
        "Args": {
          "path": "log.log",
          "rollingInterval": "Day",
          "buffered": true,
        }
      }
    ]
  }
}
```

When running my app in Debug mode, the log file ends up in the project directory instead of the ` bin\Debug\netcoreapp5.0\` directory. What figures?

**Comment by cocowalla** [comment]
I presume you are either running your project from an IDE, or using `dotnet run`? In that case, the "current directory" is the project root, so this is the expected behaviour. If instead you ran the exe from within `bin\Debug\netcoreapp5.0` (as you would in production), you would find the files logged there instead.

**Comment by cocowalla** [comment]
It's standard that they are stored relative to the current working directory, which if you're running from an IDE is the project root.

If it really bothers you, you can use environment variables in log paths (e.g. to use the standardised Windows log location: `%PROGRAMDATA%\MyApp\Logs\log.log`), or another option would be to update the path in the appsettings file to `bin\Debug\netcoreapp5.0\log.log` and use a different appsettings file in production.
