### ISSUE TITLE
retainedFileCountLimit with minimum level to error

### ISSUE THREAD

**Issue by Flavio78** [serilog/serilog-sinks-file#283]
I am trying to set a minimum level while creating a logger, as reported below:
```
new LoggerConfiguration()
.MinimumLevel.Error()
.Enrich.FromLogContext()
.WriteTo.Async(a => a.File(this.logFile, rollingInterval: RollingInterval.Day, retainedFileCountLimit: this.retention, shared: true, outputTemplate: MY_TEMPLATE))
.CreateLogger();
```
With this code, the retention is not applied, and all previous files are not deleted.
If I set the minimum level to debug, the `retainedFileCountLimit` works as expected. 

How could I fix this problem? Thanks. Best regards.

**Comment by bartelink** [comment]
Are you saying that too many files are being retained, or that they are too old?
e.g. it may be that in shared mode, the trimming only takes place when a write is about to hit disk. 
If in doubt, I'd read the logic in the impl - it's very small and readable

**Comment by bartelink** [comment]
I have not personally looked at the code, but it seems to be unlikely to be due to something specific that the File sink is doing. As I said, you should be able to figure out if there's any reason for it by reading though... As it stands U'd either do that, or work through the issue by logging as many details as possible on stack overflow so you get more eyes on it.

**Comment by bartelink** [comment]
It's just you and me here... Stack Overflow FTW ;)

**Comment by fnajera-rac-de** [comment]
I just stumbled upon this issue when having the same problem - the rolling/cleanup only triggers if the logger gets used!

So in the case above, if you never write an error message, the old files will stay there forever. My guess is that lowering the minimum level to debug did trigger some writing and that triggered the rolling.

Leaving it here in case it helps somebody else in the future.

**Comment by tkrafael** [comment]
That's by design.
Whenever a log is emitted, sink checks if it's time to roll up files.
A dirty way to do that is simply put a hourly log.error to force this behavior

This design is a tradeoff between performance VS complexity. Imagine if the rolling process run on another thread/task? It will be difficult to avoid a log to be written to a rolled file made by such task.
