### ISSUE TITLE
Implement Serilog 4.x `IBatchedLogEventSink`

### ISSUE THREAD

**Issue by Rabadash8820** [serilog/serilog-sinks-file#324]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm thinking that this sink should implement the new Serilog 4.x `IBatchedLogEventSink` interface. The `BatchingOptions` class would allow consumers to batch by time, number of items, or both, with various other options as well.

**Describe alternatives you've considered**
Using the `buffered` setting and/or [Periodic Batching](https://github.com/serilog/serilog-sinks-periodicbatching) sink is still an option, but this new native batching behavior seems like a perfect match for logging to files (or any I/O-bound sink).

**Additional context**
N/A

**Comment by nblumhardt** [comment]
Hi @Rabadash8820, thanks for the note!

I've wondered about this too; I think the last time I explored it, I concluded that because local I/O is generally buffered by the OS in the absence of `flush()` calls, the Serilog batching infrastructure would be essentially duplicating the buffering that the OS is already doing. `WriteTo.File()` accepts a `flushToDiskInterval` parameter that's in a similar spirit to the batching sink's `BufferingTimeLimit` option, and in this mode, writes are effectively batched behind the scenes in the host's I/O subsystem.

The `IBatchedLogEventSink` version would still shift some rendering/write latency from the foreground/calling thread to the background batching thread, but by keeping writes on the foreground thread we can let the I/O subsystem provide backpressure, which it will do more effectively than Serilog's channel-based implementation can.

A Serilog-batched version would also potentially lower the total number of threads involved, since I/O could be non-blocking/async. Not sure what impact this would have in practice given some of the other trade-offs.

All up it would still be interesting to spike this out and benchmark it, but it's probably pretty nuanced 🤔

**Comment by Rabadash8820** [comment]
> because local I/O is generally buffered by the OS in the absence of flush() calls, the Serilog batching infrastructure would be essentially duplicating the buffering that the OS is already doing

Yeah I was wondering about that. 🤔

> by keeping writes on the foreground thread we can let the I/O subsystem provide backpressure, which it will do more effectively than Serilog's channel-based implementation can

I don't know much about this backpressure system, so I'll take your word for it lol.

> A Serilog-batched version would also potentially lower the total number of threads involved, since I/O could be non-blocking/async

Not sure I understand this argument. Both of `IBatchedLogEventSink`'s methods are async (`Task`-returning), so thread sharing should still be pretty good, no?

One other argument _for_ implementing `IBatchedLogEventSink` would be the improved configurability. Currently, `File` can only batch "by time" with `flushToDiskInterval`, while `BatchingOptions` includes the option to batch by number of items and some other things. As implementations of `IBatchedLogEventSink` become more common, it might be nice for `File` to use the same config options as other sinks. 🤷‍♂️

**Comment by nblumhardt** [comment]
> > A Serilog-batched version would also potentially lower the total number of threads involved, since I/O could be non-blocking/async
>
> Not sure I understand this argument. Both of IBatchedLogEventSink's methods are async (Task-returning), so thread sharing should still be pretty good, no?

👍 this is what I mean; the use of async might free up some threads that would otherwise be blocked on I/O writes, though it's probably not a significant difference unless an app is primarily writing logs.

**Comment by Rabadash8820** [comment]
Oh okay I thought that you meant that as an argument _against_ implementing. While yeah, ball's in your court lol, I agree that some benchmarking is probably in order. Short of suggesting [BenchmarkDotNet](https://benchmarkdotnet.org/) I'm afraid I can't offer much help there. 🫤

**Comment by nblumhardt** [comment]
Thanks @Rabadash8820 :+1:

I think whether or not anything's attempted here will come down to someone spotting this issue, benchmarking, and showing some scenarios that exhibit improvements.

Since we're not planning to pursue the feature here currently I'll close the ticket, but we can pick it up again in the future if there's an opportunity. Thanks again!
