### ISSUE TITLE
No path formats supported

### ISSUE THREAD

**Issue by LarsWesselius** [serilog/serilog-sinks-file#36]
It seems the extension `WriteTo.File` does not support path formats like the 'old' `RollingFile` does. I see  [Specifier.cs from serilog-sinks-rollingfile](https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/Specifier.cs) and `TemplatedPathRoller` which is very similar to the `PathRoller` found in this project. 

It seems easy to support path templating here (since the code is very similar and can be transferred), but maybe I'm missing something here; was not templating in this project intentional? If so, why?

Thanks!

**Comment by amoerie** [comment]
At first glance, it would appear that these formats are now hardcoded into https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/RollingInterval.cs

**Comment by LarsWesselius** [comment]
Correct, as a result you end up with a hardcoded filename as per the README. My format is log-{Hour}.txt and the file ended up as `log-{Hour}201710241211.txt`

**Comment by nblumhardt** [comment]
@LarsWesselius thanks for the note; yes, the decision was intentional - the original design of _RollingFile_, though I really like it aesthetically, doesn't work the way people expect it to:

 * Custom `:xxx` formats aren't supported, and are unlikely to be, because they'd require translation to equivalent regular expressions in order for precise file set detection to work
 * Arbitrary properties from log events can't appear in the path, even though the syntax is identical to the output template syntax used elsewhere
 * Template placeholders can't appear in directories in the path, only files
 * Multiple templates can't appear in the same path, e.g. `/{Year}/{Month}` etc.

_File_'s rolling is making a clean break - it'd be great to implement all of these things in _RollingFile_ someday, but for a stable, core package, I think the simpler approach in _File_ is the better one for now.

@amoerie the formats are hard-coded in _Serilog.Sinks.RollingFile_ as well - https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/Specifier.cs#L22 :-)

**Comment by LarsWesselius** [comment]
Fair points, thanks.
One additional question based on your comment; you mention you'd like to implement all of those things into RollingFile but I was under the impression the File package was the new 'standard' if you will. How are these packages going to co-exist in the future?

Thanks again!

**Comment by nblumhardt** [comment]
Hi Lars,

> It is a shame though that the yyyMMddHHmm format is not editable.

I think a customizable format is a fair feature to add, I definitely wouldn't rule it out in the future, but doing a good job of it seems like it will be non-trivial. Needs a lot of careful analysis around filename parsing, anyway - having the sink delete files that it didn't create is something of a doomsday scenario :-) It would also be necessary to ensure that whatever format is used can be reliably parsed to the right resolution - `yyyy` is never going to work for a monthly rolling file, for example, and that locale doesn't cause anything crazy to happen. Need to figure out the constraints and how we might detect problems.

> How are these packages going to co-exist in the future?

_Serilog.Sinks.RollingFile_ is so widely-used I don't think it'll become "legacy" in the near future - we'll encourage people to use the _File_ package, but if someone took the lead on _RollingFile_ there's room for it to continue evolving. (Having the more conservative _File_ implementation actually takes some of the pressure off of _RollingFile_ - perhaps it can even move a bit faster now! :-))

**Comment by LarsWesselius** [comment]
Hey,

Thanks for the explanation :)
I'll keep a close eye on the projects going forward.
