### ISSUE TITLE
Environment Variables do not work on path when configuring via code

### ISSUE THREAD

**Issue by tafs7** [serilog/serilog-sinks-file#47]
When configuring the sink via code, if the `path` uses environment variables such as `%PROGRAMDATA%` or `%TMP%`, the sink does not expand those values into the string.

However, this behavior **already exists** when configuring the File sink via `appSettings`, and is even mentioned in the README.

Is that by design, or just a missed functionality?  If the latter, I vote to make the two configuration options consistent by adding expansion of those vars regardless of how you configure this sink. 

Otherwise the consuming code has to know to do something like 
```csharp
path = System.Environment.ExpandEnvironmentVariables(path);'
```
before assigning it to the `File(...)` extension method.

**Comment by tsimbalar** [comment]
Hi Thiago,

it is by design, Environment Variable is a feature provided by the *settings providers* (*Serilog.Settings.AppSettings* and *Serilog.Settings.Configuration* at the moment), but it is not part of Serilog or part of the sinks. 

This allows to have a consistent configuration behavior accross all sinks (features provided by settings providers are automatically available to all sinks), but it also means that it is not available by code. The workaround is the code that you suggested.

I hope that helps !

**Comment by tafs7** [comment]
@tsimbalar thanks for the explanation!   Perhaps adding a little note in the README to be explicit that when configuring via code, expansion is not performed?  It could save someone else a few mins of their time :)
