### ISSUE TITLE
Writing logs to files using Serilog is not working

### ISSUE THREAD

**Issue by andreipetrescu95** [serilog/serilog-sinks-file#55]
I have an ASP .NET based application that uses Serilog for logging and I want to test it by writing my logs to files. I am using Serilog and Serilog.Sinks.File So far, the code looks like this:

```
_perfLogger = new LoggerConfiguration()
                .WriteTo.File("C:\\Users\\andav\\Desktop\\NewTest\\logger\\perf.txt")
                .CreateLogger();

_perfLogger.Write(LogEventLevel.Information, "{@LogDetail}", infoToLog);
```

But all my files are empty or are not created and I am not getting any errors.

Am I doing something wrong?

Thank you.

**Comment by merbla** [comment]
Hey @andreipetrescu95,

Are you calling `CloseAndFlush`?  You might want to checkout the following links.

* https://github.com/serilog/serilog/wiki/Lifecycle-of-Loggers
* https://merbla.com/2016/07/06/serilog-log-closeandflush/

Also, if using AspNet Core, I would suggest grabbing the [package](https://github.com/serilog/serilog-aspnetcore) `Serilog.AspNetCore`.

**Comment by nblumhardt** [comment]
Closing as stale, but please chime in if you have more data @andreipetrescu95 👍

**Comment by se7vanj** [comment]
> Closing as stale, but please chime in if you have more data @andreipetrescu95 👍

@nblumhardt I am having the same issue. Using File Sink with Async, it works fine for hours and then suddenly (after days) its not writing any files. Selflog does not show any issues about this.

Appreciate if you can provide any assistance on this issue. Details below:

Earlier I was using Rolling package, AlternateRolling package and had similar issues. So decided to use File Sink to find out what's the actual problem?

I have also changed IIS AppPool setting "Disable Overlapped Recycle" to True.

1. CloseAndFlush is only to make sure that log events are not skipped during the Application Exit right? 

2. In this case its an API hosted on IIS, I felt it is working fine if I call CloseAndFlush multiple times? but that would not be a best idea?

3. I am calling the CloseAndFlush method on the AppDomain.CurrentDomain.DomainUnload event defined in Global.ASAX, my assumption is without even calling this it should run fine? (because I am not talking about any logs that was submitted seconds ago, nothing is being written, AppPool was not stopped)

 ```csharp
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
           //
	      var logger = new LoggerConfiguration()
                .MinimumLevel.ControlledBy(levelSwitch) //Dynamic levels

                // Sink 1 - SEQ
                //.WriteTo.Seq(StaticConfiguration.LogSeqServerUrl)

                // Sink 2 - FILE
                //XML configuration support has not yet been added for this wrapper, hence we have below code snippets instead fully from web.config file

                // File Sink - Async
                .WriteTo.Async(a => a.
                    File(string.Format(string.Format(filePath + ".log")),
                    rollingInterval: RollingInterval.Day,
                    outputTemplate: "{Message:lj}{NewLine}"
                    fileSizeLimitBytes: 40000000
                    shared: true
                    retainedFileCountLimit: 10
                    rollOnFileSizeLimit: true
                    //buffered: true, //not available when shared
                    //flushToDiskInterval: TimeSpan.FromMilliseconds(500)))

                .CreateLogger();


            // Configure PostSharp Logging to use Serilog
            var backend = new SerilogLoggingBackend(logger);
            backend.Options.Delimiter = ""
            backend.Options.AppendTrailingPeriod = false;
            backend.Options.UseSerilogFormatters = true;
            LoggingServices.DefaultBackend = backend;
        }
    }
 ```

**Comment by nblumhardt** [comment]
Hi @se7vanj - thanks for getting in touch. This sounds like a different issue from the one originally reported; could you please open a new ticket with the info above? I would have suggested checking `SelfLog`, but hearing there's no information being surfaced by it, I would guess the issue's either in the `Async()` implementation (in which case, check out the queue monitoring APIs it exposes), or possibly a deadlock somewhere (collecting a dump of threads/stacks from the process will help, here). HTH!

**Comment by se7vanj** [comment]
> Hi @se7vanj - thanks for getting in touch. This sounds like a different issue from the one originally reported; could you please open a new ticket with the info above? I would have suggested checking `SelfLog`, but hearing there's no information being surfaced by it, I would guess the issue's either in the `Async()` implementation (in which case, check out the queue monitoring APIs it exposes), or possibly a deadlock somewhere (collecting a dump of threads/stacks from the process will help, here). HTH!

@nblumhardt thanks, will try above. I have created a new issue as suggested.

https://github.com/serilog/serilog-sinks-file/issues/82#issue-409610390
