### ISSUE TITLE
Custom IFormatProvider is ignored by File sink

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog-sinks-file#57]
Original issue by @bitchkat in Core repo : serilog/serilog#1115

A custom `IFormatProvider` / `ICustomFormatter` implementation works fine with *Serilog.Sinks.Console* but is ignored by *Serilog.Sinks.File*.

```csharp
public class CustomDateFormatter : IFormatProvider, ICustomFormatter
{
	private readonly string _datePattern;

	/// <summary>
	/// Initializes a new instance of the <see cref="DateFormatter"/> class.
	/// </summary>
	/// <param name="datePattern">date format pattern</param>
	/// <param name="basedOn">base format provider</param>
	public CustomDateFormatter(string datePattern)
	{
		_datePattern = datePattern;
	}

	/// <summary>
	/// Gets the Formatter object
	/// </summary>
	/// <param name="formatType">format type</param>
	/// <returns>formatter</returns>
	public object GetFormat(Type formatType)
	{
		if (formatType == typeof(ICustomFormatter))
		{
			return this;
		}

		return null;
	}

	/// <summary>
	/// Formats an object for output
	/// </summary>
	/// <param name="format">optional format string, if not provided the default date pattern is used</param>
	/// <param name="arg">the object to be formatted</param>
	/// <param name="formatProvider">format provider</param>
	/// <returns>formatted string</returns>
	public string Format(string format, object arg, IFormatProvider formatProvider)
	{
		if (arg is DateTime)
		{
			return ((DateTime)arg).ToString(format ?? _datePattern);
		}
		else
		{
			try
			{
				return HandleOtherFormats(format, arg);
			}
			catch (FormatException e)
			{
				throw new FormatException($"The format of '{format}' is invalid", e);
			}
		}
	}

	/// <summary>
	/// Fallback formatter for non DateTime objects
	/// </summary>
	/// <param name="format"></param>
	/// <param name="arg"></param>
	/// <returns></returns>
	private string HandleOtherFormats(string format, object arg)
	{
		if (arg is IFormattable)
		{
			return ((IFormattable)arg).ToString(format, CultureInfo.CurrentCulture);
		}
		else if (arg != null)
		{
			return arg.ToString();
		}
		else
		{
			return string.Empty;
		}
	}
}
```

**Comment by adamchester** [comment]
Will this be due to the JSON format modifier in the default output template?

**Comment by nblumhardt** [comment]
@adamchester that's quite likely (this sink and _Console_ handle this differently...) :+1:

**Comment by nblumhardt** [comment]
(Calling this "possibly-a-bug")

**Comment by adamchester** [comment]
Possibly #1183 has related info

**Comment by tsimbalar** [comment]
Seems legit :) 

So : 
- ` `: top level strings are wrapped in double-quotes - **customizable with custom formatter**
- `:j` : machine-parsable JSON - **not customizable**
- `:l` : same as ` ` but removes quoted strings - **customizable with custom formatter**
- `:lj` : JSON for structured content + *no quotes* top level literals - **customizable with custom formatter**

That seems rather coherent to me !

**Comment by nblumhardt** [comment]
Good summary 👍 

From another angle:

- ` `: _I don't want my existing log parser to break (stable formatting since pre-1.0 days)_
- `:j` : _I want human-readable logs, but care enough about parsing them to accept some visual noise_
- `:l` : _I favor readability over anything else_
- `:lj` : _I favor readability over anything else, and prefer to read JSON-style structured data formatting_

The only slight glitch, to me, is how `DateTime`s are handled. I think, right now, the `lj` format will write ISO-8601, which is almost always more convenient than culture-aware formatting (to me), but our proposed change will flip this.

Reading the above, I think `:lj` is _currently_ the format I'd choose, while after the change, I couldn't generate this format.

Perhaps (unless others disagree strongly), we go the other way and just suggest people use `` or `:l` if they want custom/culture-aware formats? This would mean the intention is:

- ` `: _I don't want my existing log parser to break (stable formatting since pre-1.0 days)_
- `:j` : _I primarily want machine-readable logs_
- `:l` : _I primarily want human-readable logs_
- `:lj` : _I want to strike a balance - machine-readable as much as possible, but accept some compromises to remove clutter_

..and we'd consider `File` to be correct right now, and `Console` to be the one requiring modification. Any thoughts? Could be a bit of a bikeshed... :-/

**Comment by tsimbalar** [comment]
@nblumhardt I have no strong opinion, and your comments make complete sense :)

So I guess as a result : 
- https://github.com/serilog/serilog/pull/1183 should be killed .. but I would still udate/keep the tests so we have some regression testing in place for the future
- we need a new issue in `Serilog.Sink.Console` about his issue

**Comment by nblumhardt** [comment]
Closing, moving this issue to _Console_, as we've resolved that it has the less-desirable behavior.
