### ISSUE TITLE
Powershell configuration issue

### ISSUE THREAD

**Issue by jacerm** [serilog/serilog-sinks-file#58]
I am attempting to implemented Serilog in a powershell project.

I am using Serilog Core 2.7.1 and Serilog-sinks-file 4.0.0

I am unable to configure the logger to write to a file because of an argument type exception.  
The parameter `fileSizeLimitBytes` in the DLL is both nullable and has a default value set, but I can't call the method without a value for it, and when I do pass in a value, it requires the value to be of a nullable type.

![serilogsnippet](https://user-images.githubusercontent.com/10948023/41697751-244b79ac-74cf-11e8-93f8-184dc7ba067b.png)
![serilogerror](https://user-images.githubusercontent.com/10948023/41697760-29a9e17c-74cf-11e8-89a7-3d54706decf9.png)

Is there any guidance on how to implement serilog-sinks-file via powershell.

**Comment by nblumhardt** [comment]
Eek - that doesn't sound like fun :-)

Writing a small .NET EXE and invoking this from Powershell can be a lot nicer; the API's not designed for use outside C#, so although I'll pass on anything I can find about this, I'll close the ticket because I don't want to bring PowerShell support into scope for this project. Cheers!
