### ISSUE TITLE
Windows Service restart causing _001, _002, _003 files.

### ISSUE THREAD

**Issue by piotrzaremba** [serilog/serilog-sinks-file#61]
I currently have the following Ilogger configuartion.

return new LoggerConfiguration().Enrich.With<UtcTimestampEnricher>().Filter.ByExcluding(ev => !fixieOptions.IsSerilogEnabled).MinimumLevel.Debug().WriteTo.Async(appender => appender.File(Path.Combine($"{AppDomain.CurrentDomain.BaseDirectory}\\..\\logs", "telemetry", "telemetry..log"), rollingInterval: RollingInterval.Day,outputTemplate: "{UtcTimestamp}|{Level:u3}|{Message:lj}{NewLine}{Exception}")).CreateLogger();

Each time I restart my windows service a new file is created and appended with a sequence number.  The issue is that on another windows service the same configuration is used and when that service is restarted NO new file is created.  How do I prevent the _001..._00n sequence files from getting created.  I want a single file per day.

**Comment by nblumhardt** [comment]
If multiple services are writing to the same path, you'll need to add `shared: true` to the `RollingFile` configuration.

Otherwise, it's likely that the file is still being held open by another process, perhaps due to overlapped shutdown/startup, because the logger isn't being closed/disposed appropriately, or because more than one logger instance is being created per application run. Do any of these suggest a cause? Cheers!

**Comment by piotrzaremba** [comment]
That solved it I just needed to increase the wait time between when the service was shutdown and then restarted.
