### ISSUE TITLE
Support {Date} for log path

### ISSUE THREAD

**Issue by saithis** [serilog/serilog-sinks-file#64]
We would like to name our log files "appname-{Date}-{ServerId}.txt" ("{ServerId}" is replaced by our code). That way the files could be sorted by date und then by server. But currently we cant decide where the date part should be and it is always appended at the end.

**Comment by nblumhardt** [comment]
Hi! Thanks for the note; this is something supported currently in _Serilog.Sinks.RollingFile_, so at least in the short-term, using that package may be a useful alternative (if you're not reliant on other features not supported, there).

I'd personally like to avoid taking the API down this path, here, because we were never quite able to achieve seamlessness in the way `{Date}` is handled in _RollingFile_ - formatting placeholders don't work as expected, for example, making it a weak analogy with the message/output templates supported elsewhere in Serilog.

One possibility might be to insert a marker character like `*` into the filename, here - e.g.:

```
WriteTo.File("appname-*-foo.txt")
```

which should be effectively non-breaking as `*` would be a very unusual character to see in a log file name, in the wild.

The main things to then determine would be:

 * How would this affect the code that identifies files belonging to the rolling set? (Would prefer that this stays ultra-simple), and,
 * What effect would this have on the numeric file set component - would the above produce `appname-20181019-foo_001.txt` or `appname-20181019_001-foo.txt`, and if so, would this lead to ambiguities when trying to identify files in the rolling set?

These could be non-issues; it'd be great if someone has the time to figure out a solid proposal around this 👍

**Comment by yhvicey** [comment]
What about providing a `Func<string>` as the path generator to `WriteTo.File(...)`? Or some class like `FilePathGenerator` and then we can derive & override it, as an advanced option.

**Comment by Jehoel** [comment]
I've created a PR for this, albiet using a different synax here: https://github.com/serilog/serilog-sinks-file/pull/84

**Comment by tettsuan** [comment]
I have one possible solution. you can use Serilog-Sink-Map to achieve this.
I haven't taken a deep look so the inpact of using that package is not cleared.
```
Log.Logger = new LoggerConfiguration()
    .WriteTo.Map<string>(
         e => DateTime.Now.ToString("yyyyMMdd"),
         (v, wt) => wt.File($"./logs/{v}_log.txt"))
    .CreateLogger();
```

**Comment by malcolmjerry** [comment]
Try this 

 
    private readonly Serilog.ILogger _logger; //= Log.ForContext( "Name", "Weather" );

    public WeatherForecastController() {
      string subPath = Path.Combine( DateTime.Now.ToString( "yyyy" ), DateTime.Now.ToString( "MM" ) ) + $"/{DateTime.Now.ToString("dd")}_Weather";
      _logger = Log.ForContext( "Name", subPath );
    }

//////////////////////////////////////////////////////////////////////////////////////////

      .UseSerilog( ( hostingContext, loggerConfiguration ) => loggerConfiguration
        .ReadFrom.Configuration( hostingContext.Configuration )
        .Enrich.FromLogContext()
        .WriteTo.Console()
        .WriteTo.Map(
          "Name",
          "Request",
          ( name, wt ) => {
            if (name == "Request")
              wt.RollingFile( Path.Combine( $"{hostingContext.Configuration["LogPath"]}/{{Date}}-{name}.txt" ) );
            else
              wt.File( $"{hostingContext.Configuration["LogPath"]}/{name}.txt" );
          } )
      );

**Comment by BasieP** [comment]
Love having this.
Right now i can magicly add the date to my files by code, using code like this:
```
loggerConfig = loggerConfig.WriteTo.File("./logs/log-.txt", rollingInterval: RollingInterval.Day);
```
where the file sink magicly adds the date

But if i don't want to hardcode my file path, so i want to use the appsettings.json or any other configuration file.
Right now the _deprecated_ RollingFile sink _does_ support this feature. And right now i can't switch to the file sink because it would be a step back.

I would like this to work:
```
 "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "logs/log-{Date}.txt"
        }
      }
    ]
```

**Comment by BasieP** [comment]
wauw.. this from 2018..

Here i was thinking serilog had a decent team behind it supporting the product..
Perhaps time to go back to log4net 👎

**Comment by BasieP** [comment]
> Hi! Thanks for the note; this is something supported currently in _Serilog.Sinks.RollingFile_, so at least in the short-term, using that package may be a useful alternative (if you're not reliant on other features not supported, there).
> 
> I'd personally like to avoid taking the API down this path, here, because we were never quite able to achieve seamlessness in the way `{Date}` is handled in _RollingFile_ - formatting placeholders don't work as expected, for example, making it a weak analogy with the message/output templates supported elsewhere in Serilog.
> 
> One possibility might be to insert a marker character like `*` into the filename, here - e.g.:
> 
> ```
> WriteTo.File("appname-*-foo.txt")
> ```
> 
> which should be effectively non-breaking as `*` would be a very unusual character to see in a log file name, in the wild.
> 
> The main things to then determine would be:
> 
> * How would this affect the code that identifies files belonging to the rolling set? (Would prefer that this stays ultra-simple), and,
> * What effect would this have on the numeric file set component - would the above produce `appname-20181019-foo_001.txt` or `appname-20181019_001-foo.txt`, and if so, would this lead to ambiguities when trying to identify files in the rolling set?
> 
> These could be non-issues; it'd be great if someone has the time to figure out a solid proposal around this 👍

i don't think you get the issue here.
right now there is NO way to add the date to your files using only configuration.

when i don't add anything using the file sink. i get a filename that is only named. 'log.txt'
there is no date..

**Comment by cocowalla** [comment]
While the `{Date}` syntax was only used in the deprecated [serilog-sinks-rolling file](https://github.com/serilog/serilog-sinks-rollingfile) project, as long as you specify a rolling interval with `rollingInterval`, a timestamp will *automatically be added* to the end of the filename.

**Comment by nblumhardt** [comment]
@BasieP 

> wauw.. this from 2018..
>
> Here i was thinking serilog had a decent team behind it supporting the product..
> Perhaps time to go back to log4net 👎

Actually, it works the other way. Serilog is a community project, and it's made it to where it is today because it has an awesome _community_ behind it. No one promised to work for you for free: if you want Serilog to advance, you need to contribute constructively. Please refrain from this kind of incivility, thanks.

**Comment by nblumhardt** [comment]
All, I think this issue is stale: if anywhere, I think a plan to support this in _RollingFile_ would be the best bet, although as others on this thread have pointed out, _Map_ provides a reasonable option too. Open to plans/PRs, but in favor of closing this. @cocowalla ?

**Comment by cocowalla** [comment]
@nblumhardt makes sense to close, as the feature request is basically covered by the functionality I described in my previous comment.

**Comment by aleripe** [comment]
It is not covered. as every organization has its own way of defining the file name, and date is not always at the end...

**Comment by bartelink** [comment]
@Ernest314 Can you not cover your needs with [`Map`](https://github.com/serilog/serilog-sinks-file/issues/64#issuecomment-613692238) ?

In general I am a big fan of the simplicity of the `File` sink - there's little to go wrong so you can just trust it (IME as opposed to competing impls which I;ve spent days analysing crash dumps and perf degradation scenarios in before concluding the answer was to port to Serilog). Adding features is thus definitely something to avoid; while I appreciate that there are cases where specific naming format requirements arise, I'd venture that they're rarer than they appear fro the perspective of someone who has the need...

(See similar ground being tread in #40 - there are forked File sinks such as https://github.com/dfacto-lab/serilog-sinks-file/ which cover bells and whistles that are hard to implement cleanly and/or not relevant to the vast majority of users - obviously that's a more complex change than the one being requested here, but the point is trying really hard to not add complexity to the File Sink)

**Comment by Ernest314** [comment]
That is fair, the solution I landed on did end up using Map, but it seemed very verbose and unwieldy for what I expected would be a simple task. That said, "rarer than they appear from the perspective of someone who has the need" is certainly also a valid point. I do defer to that judgment of what is worth including in the basic library, and I appreciate the clarification on the reasoning behind the decision.

**Comment by Jehoel** [comment]
My ears are burning...

Is there still any interest in having me resurrect #84 ?

**Comment by nblumhardt** [comment]
Hi @Jehoel! :wave:

I think when we left it we had maybe three workable options on the table:

### 1. Support `*` in filenames, in the current sink, and insert formatted rolling path component there

This would be a limited scope change that should be backwards-compatible, but but would still bring along a few edge cases to be wary of (e.g.  `test*_001.txt`, probably more to find). I don't think we'd go as far as supporting `*` in directory names, since there's only one path component to format in.

The main downside of this one is that it's not going to please everybody, and so we'll still be fielding requests for various tweaks on the rolling scheme for years on end even if we do this :-)

### 2. Support something like the `{yyyy}` and `{MM}` placeholders in path components

Covers a lot more cases/will please more people, but carries more risk - specifying it is trickier, it may need more configuration (delete empty dirs once files have rolled out of them etc.), and it seems tougher to guarantee we'll correctly identify which files belong to the file set, and won't ever be at risk of deleting the wrong files.

### 3. Ship a companion library that wraps _Serilog.Sinks.File_ to implement something like (2)

This is essentially (2), but would allow for iteration. I believe that the newer hooks (`FileLifecycleHooks`, `LoggerSinkConfiguration.Wrap()`) would allow the file writing functionality in _Serilog.Sinks.File_ to be reused, while the rolling logic would be completely rewritten (and would need to be).

There's really nothing at all blocking 3 right now, so this would be the best place for anyone who can dedicate time to it to get started. I'd be glad to help with pointers/answer questions etc. if you or anyone else following along on this thread is keen to kick it off. _Serilog.Sinks.FlexibleFile_? 🤔 

---

In the end, the main thing holding us back from jumping on this in _Serilog.Sinks.File_ is that we want this project to be a very tight, easily maintainable implementation that can support many (up to millions?) of users without a big team behind it. So far that strategy seems to be working pretty well, in that we're still here keeping the package fresh, investigating bug reports, and adding quality-of-life improvements where we can.

Another big benefit of the simplicity and stability of this package is that it still makes a good building block for others to implement more complex scenarios; I'm really keen to see someone who wants this feature take (3) and run with it, kudos to you if you have the time and inclination 👍

**Comment by Jehoel** [comment]
@nblumhardt I don't recall discussing all 3 of those options though - I only remember discussing option 2.

[But I'll pull you back to 2019](https://github.com/serilog/serilog-sinks-file/pull/84) (before Covid! Those were the days...) where my implementation used a different approach to those 3: it's essentially [just raw .NET `DateTime` custom-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) with embedded literals for custom text, including literal slashes for directory separators.

* The two main reasons for me choosing that approach are:: 
  1. Familiarity: everyone writing for .NET is already familiar with Date+Time custom format strings (and I'm sure we've all learned the hard way that `HH:mm` is completely different to `h:MM`, heh.
  2. It _instantly solves_ the reverse filename parsing problem by taking advantage of .NET's built-in (and robust!) format-string-based `DateTime.Parse` and `ParseExact` methods, all without needing to write any kind of parser or formatting system ourselves.
    * (For those unfamiliar with Serilog's internals: custom log filename formats aren't just for generating new file-names, but they also need to be parsed back in (i.e. reverse) so Serilog can identify which old/expired log files can be dropped - or rotated - or overwritten  - this is why it's not as simple as just using [.NET Composite Format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting) - otherwise we'd be forced to require users to specify both a filename composite format string _and_ a regex that reliably matches those same filenames - which just isn't a feasible option.
    * Not to mention the problem that it's easy to write certain composite-format strings that's are almost impossible to reliably parse back in with a regex. Remember that regexes [aren't _that_ powerful](https://en.wikipedia.org/wiki/Chomsky_hierarchy) in the grand scheme of things: sitting at the very bottom of the Chomsky hierarchy.

ANYWAY

My current position as-of right now in June 2022 is that I still think that using _non-composite_ .NET date+time format strings remains the _simplest_ solution - you did raise 2 technical problems with this approach which I believe have straightforward solutions:

> For example, reusing .NET DateTime format strings is advantageous in some ways (existing docs, parser, formatter), but it seems to force the separation of the parent directory from the subdirectory format, which wouldn't be necessary if we were to use a template syntax like `pathFormat: "C:\SomeDir\{yyyy}\log-{MM-dd}.txt".`

But this isn't a problem: _non-composite_ Custom .NET Date+Time format strings can contain arbitrary literal text, including slashes denoting directory separators.

So for example, my proposal's equivalent of your `pathFormat` string would be `@"""C:\\SomeDir\\""yyyy""\\log-""MM-dd"".txt""" - which is trivial to demonstrate working both-ways in Linqpad:

![image](https://user-images.githubusercontent.com/1693078/172578803-d61daae7-2854-49a5-a031-520ef24a93bc.png)

> The .NET DateTime format syntax is also might paint us into a corner. How would the syntax be extended to allow selected placement of numeric filename components like `_001`, for example? Not un-solveable problems, but seems better to consider these kinds of complications from the outset, rather than graft them on later.

* **Horrible hack solution**: Repurpose the `fff` format specifier for the sequential file number.
   * (No-one _really_ uses millisecond-level precision in their filenames, right?)
   * So when generating a new filename from `DateTime.UtcNow`, you'd cache `UtcNow`, zero-out and re-set `Millisecond` to the next sequential number.
   * And when parsing filenames back to timestamps, if the format-string contains a non-escaped `f`/`ff`/`fff` specifier then after parsing use the parsed-value's `Millisecond` property for the sequence number. Be sure to zero-out the `Millisecond` property if the parsed value will be used anywhere else, of course.
* _Less-horrible but imperfect_: Simply _always_ render the sequence-number immediately before the file-extension, allowing it to be inserted after filename generation - and be removed from the file path string before it's parsed.
* _Also horrible_: use some magic literal as a placeholder? It could be a character that's illegal in Windows filenames, like `?` or `*` - because sequence-numbers will always be rendered as `\d+` then a regex could be used to match them and patch filenames before-and-after parsing or generation.
* I'm just spitballing here :)

------

## Alternative X/Y Solution:

Instead of even attempting to parse date+times out from filenames, instead use a separate activity-log file (opened with an exclusive-lock, of course) which would be some kind of file (don't say JSON...) that associates those arbitrary log files' filenames with their metadata - and this option allows us to store even more metadata than could normally be put into a filename anyway, such as _exactly_ what filters or transformations were/are applied to that specific log-file - I hope this activity-log-file could also be even used as a way of detecting dropped-events if it were also some kind of write-ahead-log or meta-log.

**Comment by nblumhardt** [comment]
Option 1 is discussed [earlier in this thread](https://github.com/serilog/serilog-sinks-file/issues/64#issuecomment-431189142).

Sounds like you've done a stack of thinking about this; I guess this is the other great thing about option 3, it's ultimately up to you how you want the configuration to work. And it sounds like you've got a great plan 😎 - looking forward to following along. If you post a link to the repo here, I'll flip over to it and "Watch" so that I can (hopefully) help where possible. Cheers!

**Comment by He-Hao** [comment]
.WriteTo.Logger(lc => lc
       .Filter.ByIncludingOnly(evt => evt.Level == LogEventLevel.Debug)
        .WriteTo.Map<string>(
            e => DateTime.Now.ToString("yyyyMMddHHmm"),
            (v, wt) => wt.File($"D:\\Logs\\{v}\\Debug.txt", rollOnFileSizeLimit: true)
       )
   )
   .CreateLogger();

**Comment by sorcerb** [comment]
> ```
>    .WriteTo.Logger(lc => lc
>        .Filter.ByIncludingOnly(evt => evt.Level == LogEventLevel.Debug)
>         .WriteTo.Map<string>(
>             e => DateTime.Now.ToString("yyyyMMddHHmm"),
>             (v, wt) => wt.File($"D:\\Logs\\{v}\\Debug.txt")
>        )
>    )
>    .CreateLogger();
> ```
> 
> [Serilog.Sinks.Map](https://www.nuget.org/packages/Serilog.Sinks.Map)

Hardcode log settings isn't good...

> Configuration with <appSettings> and appSettings.json
> Serilog.Sinks.Map is built around a mapping function, and as such, isn't able to be configured using XML or JSON configuration.
