### ISSUE TITLE
Support for Encrypting Log Files

### ISSUE THREAD

**Issue by DenisDolgunov** [serilog/serilog-sinks-file#71]
If have some plans to add encrypting files in the project, what's best practice for do it?

**Comment by cocowalla** [comment]
There is some discussion on compression in #48, which very much relates to file encryption. Like compression, there are 2 approaches to encrypting files:

1. Streaming
2. All at once when the log is closed/rolled

For encryption, you would generally want the 1st option, to ensure the plaintext was never written to disk in the first place.

I have a fork that allows wrapping the output stream [here](https://github.com/cocowalla/serilog-sinks-file/tree/feature/streaming-compression). The use case being demonstrated was compression, but I had encryption in mind too - the point is that wrapping the output stream is an extensible approach that allows for a variety of use cases.

**Comment by nblumhardt** [comment]
Note this may be covered by #80.

**Comment by nblumhardt** [comment]
I think we should close this as "optimistically, enabled by #80", which is now on NuGet in the -dev preview package. If it turns out the file lifecycle hooks we currently support are inadequate, we can open a new ticket and follow on from there.

Let us know if you take a shot at this, @DenisDolgunov - happy to help with the details.

**Comment by cocowalla** [comment]
@DenisDolgunov now #80 is in `dev`, can you say a bit more about your use case? A few questions:

1. Where will your key material come from (e.g. X.509 certificate or key, config file, environment variable, API call)?

2. What algorithm(s) did you have in mind?

3. Had you given any thought to a MAC or cryptographic signature?

**Comment by byte2pixel** [comment]
7 years later.

I've attempted to tackle this for my own knowledge and potential for some desktop software for my job as well.  We currently use trace logging with trace events and listeners, and do encryption and hashing as well.  I'm pushing to move to structured logging and need it to keep the features.

I created this hook. It is a very early alpha, and any feedback is appreciated.

Obviously, with encryption involved, it would **not** be ideal to use when you need raw performance.  I did try to keep it as fast as possible using hybrid encryption.

https://github.com/byte2pixel/serilog-sinks-file-encrypt

I'm posting here because I recall this being like the first hit when I tried to find something for encrypting structured logs.

Cheers,
Mel

----
edit: **not** ideal to use when you need raw performance.

**Comment by nblumhardt** [comment]
Awesome! Thanks Mel 👍

**Comment by thch-cubido** [comment]
> 7 years later.
> 
> I've attempted to tackle this for my own knowledge and potential for some desktop software for my job as well. We currently use trace logging with trace events and listeners, and do encryption and hashing as well. I'm pushing to move to structured logging and need it to keep the features.
> 
> I created this hook. It is a very early alpha, and any feedback is appreciated.
> 
> Obviously, with encryption involved, it would **not** be ideal to use when you need raw performance. I did try to keep it as fast as possible using hybrid encryption.
> 
> https://github.com/byte2pixel/serilog-sinks-file-encrypt
> 
> I'm posting here because I recall this being like the first hit when I tried to find something for encrypting structured logs.
> 
> Cheers, Mel
> 
> edit: **not** ideal to use when you need raw performance.

Had a look at the source. Why not use a stream cipher instead of a block cipher? E.g. [ChaCha20](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.chacha20poly1305?view=net-10.0).

**Comment by byte2pixel** [comment]
> Had a look at the source. Why not use a stream cipher instead of a block cipher? E.g. [ChaCha20](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.chacha20poly1305?view=net-10.0).

I used what I was familiar with to get the concept working.

**Comment by thch-cubido** [comment]
> > Had a look at the source. Why not use a stream cipher instead of a block cipher? E.g. [ChaCha20](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.chacha20poly1305?view=net-10.0).
> 
> I used what I was familiar with to get the concept working.

Ok. I made a PR
