### ISSUE TITLE
Hook for Writing to a Log File on Close

### ISSUE THREAD

**Issue by define-private-public** [serilog/serilog-sinks-file#81]
Hi,  I really like this logging framework;  thanks for making it.

I'm right now developing console/desktop apps, not something like a daemon or webapp which is supposed to stay alive for a long time.  I have two sinks being used right now Console & File.  I'm wondering if there is some way I could output a "break line" (say the character '-' repeated 80 times on it's own line), for the File sink when the Log is being destroyed or flushed.

That way it would be much easier to discern between multiple runs in the single log file.

**Comment by nblumhardt** [comment]
I think #80 will cover this 👍

**Comment by nblumhardt** [comment]
Hi! Version `4.1.0-dev-00833` on NuGet now supports this, but as a header rather than as a footer; check out:

https://github.com/serilog/serilog-sinks-file/blob/dev/test/Serilog.Sinks.File.Tests/FileSinkTests.cs#L187

Via: #80

`FileHeaderWriter` in the test project is only an example; by tweaking the logic in there, the `---` line could be written only when the file being opened already contains content. I think this will prove more reliable than trying to write on close, as process crashes etc. might prevent it from being called.

If you need a hand to wire it up, please let me know. I'll close this ticket, but if you end up with a snippet showing how it's done, please feel free to post it (or your feedback) in the comments :-)

**Comment by define-private-public** [comment]
I have this on my TODO list to plug this in and see how it works.

**Comment by define-private-public** [comment]
Here's what I did.  I put this somewhere:

```csharp
    /// <summary>
    /// On every launch, will add a note at the top to signify the start of the log
    /// </summary>
    public class LaunchHeader : FileLifecycleHooks
    {
        public string Header { get; }

        public LaunchHeader(string header)
        {
            Header = header;
        }

        public override Stream OnFileOpened(Stream underlyingStream, System.Text.Encoding encoding)
        {
            // Always write a new header
            var writer = new StreamWriter(underlyingStream, encoding);
            writer.WriteLine();
            writer.WriteLine();
            writer.WriteLine(Header);
            writer.WriteLine(DateTime.Now);
            writer.WriteLine();
            writer.Flush();
            underlyingStream.Flush();

            return base.OnFileOpened(underlyingStream, encoding);
        }
    }
```

And this is when I'm configuring the log (at startup):

```csharp
var logger = new LoggerConfiguration()
  .MinimumLevel.Debug()
  .WriteTo.File(
    "log.txt",
    hooks: new LaunchHeader(new string('=', 80))
  )
  .CreateLogger();
```

**Comment by cocowalla** [comment]
@define-private-public I also have a [https://github.com/cocowalla/serilog-sinks-file-header](url) for this. At present it only inserts the header for new files, but I'll add an issue to make this configurable.
